-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    balance MONEY NOT NULL,
    seller BOOLEAN NOT NULL
);

CREATE TABLE Categories (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cat_name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    descr VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    category_id INT NOT NULL REFERENCES Categories(id),
    available BOOLEAN DEFAULT TRUE,
    seller_id INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Users(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    amount MONEY NOT NULL,
    number_of_items INT NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE Carts (
    id INT NOT NULL UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    product VARCHAR(255),
    product_id INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    seller INT REFERENCES Users(id),
    saved_for_later INT NOT NULL CHECK(saved_for_later = 1 or saved_for_later = 0) DEFAULT 0
    );

-- CREATE TABLE Feedback (
--     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     uid INT NOT NULL REFERENCES Users(id),
--     pid INT NOT NULL REFERENCES Products(id),
--     review VARCHAR(1000) NOT NULL,
--     rating INT NOT NULL,
--     creation_date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
-- );

-- CREATE TABLE Inventory (
--     seller_id INT NOT NULL REFERENCES Users(id),
--     pid INT NOT NULL REFERENCES Products(id),
--     quantity INT NOT NULL,
--     price_per_item MONEY NOT NULL,
--     PRIMARY KEY(seller_id, pid)
-- );

CREATE TABLE Review_Of_Product (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    rating INT NOT NULL,
    typeshit VARCHAR(500) NOT NULL,
    review VARCHAR(1000) NOT NULL,
    time_reviewed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    CHECK (rating >= 0),
    CHECK (rating <= 5),
    num_votes INT NOT NULL DEFAULT 0,
    imagepath VARCHAR(255)
);

CREATE TABLE Review_Of_Seller (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rater_id INT NOT NULL REFERENCES Users(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    rating INT NOT NULL,
    review VARCHAR(1000) NOT NULL,
    time_reviewed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    UNIQUE(rater_id, seller_id)
);

CREATE TABLE User_Upvotes_Product_Review (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rater_id INT NOT NULL REFERENCES Users(id),
    product_review_id INT NOT NULL REFERENCES Review_Of_Product(id)
);



